// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtGU55_8ksCiqcqyyG5SOs0hQ9qzPYVls',
    appId: '1:976269825485:web:3f29e61bfbb7fbc01e2084',
    messagingSenderId: '976269825485',
    projectId: 'sampoorna-2a226',
    authDomain: 'sampoorna-2a226.firebaseapp.com',
    storageBucket: 'sampoorna-2a226.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnCPJHyHf7GlPNCakCzPTYSTFvlIwQ0EQ',
    appId: '1:976269825485:android:5ff0dba661be47fd1e2084',
    messagingSenderId: '976269825485',
    projectId: 'sampoorna-2a226',
    storageBucket: 'sampoorna-2a226.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRJI8JJUCbUDz25qSgF8w4k-ZVZgRsBGg',
    appId: '1:976269825485:ios:38b38e60201a79eb1e2084',
    messagingSenderId: '976269825485',
    projectId: 'sampoorna-2a226',
    storageBucket: 'sampoorna-2a226.appspot.com',
    iosBundleId: 'com.example.hackathonProj',
  );
}
